//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.21 at 02:15:58 PM EEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dayType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dayNumber" type="{http://www.exapmle.com/year.xsd}dayNumberType"/&gt;
 *         &lt;element name="temperature" type="{http://www.exapmle.com/year.xsd}temperatureType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dayType", propOrder = {
    "dayNumber",
    "temperature"
})
public class DayType {

    @XmlSchemaType(name = "integer")
    protected int dayNumber;
    @XmlSchemaType(name = "integer")
    protected int temperature;

    /**
     * Gets the value of the dayNumber property.
     * 
     */
    public int getDayNumber() {
        return dayNumber;
    }

    /**
     * Sets the value of the dayNumber property.
     * 
     */
    public void setDayNumber(int value) {
        this.dayNumber = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     */
    public int getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     */
    public void setTemperature(int value) {
        this.temperature = value;
    }

    @Override
    public String toString() {
        return "dayNumber: " + dayNumber +
                ", temp: " + temperature + "\n" ;
    }
}
