//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.21 at 02:15:58 PM EEST 
//


package model;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for monthType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="monthType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="monthName" type="{http://www.exapmle.com/year.xsd}monthNameType"/&gt;
 *         &lt;element name="day" type="{http://www.exapmle.com/year.xsd}dayType" maxOccurs="31" minOccurs="28"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monthType", propOrder = {
        "monthName",
        "day"
})
public class MonthType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MonthNameType monthName;
    @XmlElement(required = true)
    protected List<DayType> day;

    /**
     * Gets the value of the monthName property.
     *
     * @return possible object is
     * {@link MonthNameType }
     */
    public MonthNameType getMonthName() {
        return monthName;
    }

    /**
     * Sets the value of the monthName property.
     *
     * @param value allowed object is
     *              {@link MonthNameType }
     */
    public void setMonthName(MonthNameType value) {
        this.monthName = value;
    }

    /**
     * Gets the value of the day property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore, any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the day property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDay().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DayType }
     */
    public List<DayType> getDay() {
        if (day == null) {
            day = new ArrayList<DayType>();
        }
        return this.day;
    }

    @Override
    public String toString() {
        return "Month " +
                monthName + "\n" +
                day.stream().sorted(Comparator.comparingDouble(DayType::getDayNumber))
                        .map(DayType::toString)
                        .collect(Collectors.joining(""));

    }
}
